/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.project;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Owais
 */
public class menu extends javax.swing.JFrame {
//class variables

    Board b = new Board();
    Generator g = new Generator(b);

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        grid00 = new javax.swing.JLabel();
        grid01 = new javax.swing.JLabel();
        grid02 = new javax.swing.JLabel();
        grid03 = new javax.swing.JLabel();
        grid04 = new javax.swing.JLabel();
        grid05 = new javax.swing.JLabel();
        grid06 = new javax.swing.JLabel();
        grid07 = new javax.swing.JLabel();
        grid08 = new javax.swing.JLabel();
        grid09 = new javax.swing.JLabel();
        grid10 = new javax.swing.JLabel();
        grid11 = new javax.swing.JLabel();
        grid12 = new javax.swing.JLabel();
        grid13 = new javax.swing.JLabel();
        grid14 = new javax.swing.JLabel();
        grid15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 248, 239));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(250, 248, 239));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/project/bg.png"))); // NOI18N
        jLabel17.setFocusable(false);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(100, 130, 400, 400);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new java.awt.GridLayout(4, 4, 10, 10));

        grid00.setBackground(new java.awt.Color(205, 192, 180));
        grid00.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid00.setOpaque(true);
        jPanel1.add(grid00);

        grid01.setBackground(new java.awt.Color(205, 192, 180));
        grid01.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid01.setOpaque(true);
        jPanel1.add(grid01);

        grid02.setBackground(new java.awt.Color(205, 192, 180));
        grid02.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid02.setOpaque(true);
        jPanel1.add(grid02);

        grid03.setBackground(new java.awt.Color(205, 192, 180));
        grid03.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid03.setOpaque(true);
        jPanel1.add(grid03);

        grid04.setBackground(new java.awt.Color(205, 192, 180));
        grid04.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid04.setOpaque(true);
        jPanel1.add(grid04);

        grid05.setBackground(new java.awt.Color(205, 192, 180));
        grid05.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid05.setOpaque(true);
        jPanel1.add(grid05);

        grid06.setBackground(new java.awt.Color(205, 192, 180));
        grid06.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid06.setOpaque(true);
        jPanel1.add(grid06);

        grid07.setBackground(new java.awt.Color(205, 192, 180));
        grid07.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid07.setOpaque(true);
        jPanel1.add(grid07);

        grid08.setBackground(new java.awt.Color(205, 192, 180));
        grid08.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid08.setOpaque(true);
        jPanel1.add(grid08);

        grid09.setBackground(new java.awt.Color(205, 192, 180));
        grid09.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid09.setOpaque(true);
        jPanel1.add(grid09);

        grid10.setBackground(new java.awt.Color(205, 192, 180));
        grid10.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid10.setOpaque(true);
        jPanel1.add(grid10);

        grid11.setBackground(new java.awt.Color(205, 192, 180));
        grid11.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid11.setOpaque(true);
        jPanel1.add(grid11);

        grid12.setBackground(new java.awt.Color(205, 192, 180));
        grid12.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid12.setOpaque(true);
        jPanel1.add(grid12);

        grid13.setBackground(new java.awt.Color(205, 192, 180));
        grid13.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid13.setOpaque(true);
        jPanel1.add(grid13);

        grid14.setBackground(new java.awt.Color(205, 192, 180));
        grid14.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid14.setOpaque(true);
        jPanel1.add(grid14);

        grid15.setBackground(new java.awt.Color(205, 192, 180));
        grid15.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        grid15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid15.setOpaque(true);
        jPanel1.add(grid15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(110, 140, 380, 380);

        jLabel18.setBackground(new java.awt.Color(237, 194, 46));
        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(249, 246, 242));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("2048");
        jLabel18.setOpaque(true);
        getContentPane().add(jLabel18);
        jLabel18.setBounds(250, 10, 110, 100);

        setSize(new java.awt.Dimension(616, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // up down right left
        switch (evt.getKeyCode()) {
            case 'W' ->
                update("up");
            case 'A' ->
                update("left");
            case 'S' ->
                update("down");
            case 'D' ->
                update("right");
            case ' ' ->
                update(" ");
        }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // nullify
        switch (evt.getKeyCode()) {
            case 'W' ->
                update("");
            case 'A' ->
                update("");
            case 'S' ->
                update("");
            case 'D' ->
                update("");

        }
    }//GEN-LAST:event_formKeyReleased
//gameover function
    private void isGameOver(){
        if(!b.gameOn()){
                    //game over
                    //make some dialog box that says gameover
                    System.out.println("Game over");
                }
    }
//update function
    private void update(String swipe) {

        //update from swipes
        System.out.println(swipe);
        int s=g.swipe(swipe);
        System.out.println(s);
        switch (swipe) {
            case "up" -> {
                if(s == 1 ){
                    
                g.addTile();
            }
                renderAll(b.getBoard());
                isGameOver();
            }
            case "down" -> {
                if(s==1){
                g.addTile();
            }
                renderAll(b.getBoard());
                isGameOver();
            }
            case "right" -> {
                if(s==1){
                g.addTile();
            }
                renderAll(b.getBoard());
                isGameOver();
            }
            case "left" -> {
                if(s==1){
                g.addTile();
            }
                renderAll(b.getBoard());
                isGameOver();
            }
            case " " -> {
                b = new Board();
                g = new Generator(b);
                renderAll(b.getBoard());
                isGameOver();
            }
            default->{
            renderAll(b.getBoard());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //set colour
            Color c = new Color(250, 248, 239);
            menu m = new menu();
            m.getContentPane().setBackground(c);
            m.setVisible(true);
        });

    }
//set box value

    public void setTile(JLabel x, int val) {
        //convert int to string
        String value = String.valueOf(val);
        //set tile values for color and value
        switch (val) {
            case 0 -> {
                x.setBackground(new Color(205, 192, 180));
                x.setForeground(new Color(0, 0, 0));
                x.setText("");
            }
            case 2 -> {
                x.setBackground(new Color(238, 228, 218));
                x.setForeground(new Color(119, 110, 101));
                x.setText(value);
            }
            case 4 -> {
                x.setBackground(new Color(237, 224, 200));
                x.setForeground(new Color(119, 110, 101));
                x.setText(value);
            }
            case 8 -> {
                x.setBackground(new Color(242, 177, 121));
                x.setForeground(new Color(249, 246, 242));
                x.setText(value);
            }
            case 16 -> {
                x.setBackground(new Color(245, 149, 99));
                x.setForeground(new Color(249, 246, 242));
                x.setText(value);
            }
            case 32 -> {
                x.setBackground(new Color(246, 124, 95));
                x.setForeground(new Color(249, 246, 242));
                x.setText(value);
            }
            case 64 -> {
                x.setBackground(new Color(246, 94, 59));
                x.setForeground(new Color(249, 246, 242));
                x.setText(value);
            }
            case 128 -> {
                x.setBackground(new Color(237, 207, 114));
                x.setForeground(new Color(249, 246, 242));
                x.setText(value);
            }
            case 256 -> {
                x.setBackground(new Color(237, 204, 97));
                x.setForeground(new Color(249, 246, 242));
                x.setText(value);
            }
            case 512 -> {
                x.setBackground(new Color(237, 200, 80));
                x.setForeground(new Color(249, 246, 242));
                x.setText(value);
            }
            case 1024 -> {
                x.setBackground(new Color(237, 197, 063));
                x.setForeground(new Color(249, 246, 242));
                x.setText(value);
            }
            case 2048 -> {
                x.setBackground(new Color(237, 194, 46));
                x.setForeground(new Color(249, 246, 242));
                x.setText(value);
            }
            default -> {
                x.setBackground(new Color(60, 58, 50));
                x.setForeground(new Color(249, 246, 242));
                x.setText(value);
            }
        }
    }

    public void render(int index, int val) {
        switch (index) {
            case 00 ->
                setTile(grid00, val);
            case 01 ->
                setTile(grid01, val);
            case 02 ->
                setTile(grid02, val);
            case 03 ->
                setTile(grid03, val);
            case 04 ->
                setTile(grid04, val);
            case 05 ->
                setTile(grid05, val);
            case 06 ->
                setTile(grid06, val);
            case 07 ->
                setTile(grid07, val);
            case 8 ->
                setTile(grid08, val);
            case 9 ->
                setTile(grid09, val);
            case 10 ->
                setTile(grid10, val);
            case 11 ->
                setTile(grid11, val);
            case 12 ->
                setTile(grid12, val);
            case 13 ->
                setTile(grid13, val);
            case 14 ->
                setTile(grid14, val);
            case 15 ->
                setTile(grid15, val);

        }
    }

    private void renderAll(int[] values) {
        for (int i = 0; i < 16; i++) {
            render(i, values[i]);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel grid00;
    private javax.swing.JLabel grid01;
    private javax.swing.JLabel grid02;
    private javax.swing.JLabel grid03;
    private javax.swing.JLabel grid04;
    private javax.swing.JLabel grid05;
    private javax.swing.JLabel grid06;
    private javax.swing.JLabel grid07;
    private javax.swing.JLabel grid08;
    private javax.swing.JLabel grid09;
    private javax.swing.JLabel grid10;
    private javax.swing.JLabel grid11;
    private javax.swing.JLabel grid12;
    private javax.swing.JLabel grid13;
    private javax.swing.JLabel grid14;
    private javax.swing.JLabel grid15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
